### ISSUE TITLE
Experiment with removing attributes to simplify data needed by the component

### ISSUE THREAD

**Issue by David-OFN-CA** [openfoodfoundation/sib-discovery-components#64]
I'm experimenting with a minimal version like this:
```html
<solid-ofn-rpp
      producers-src="https://api.regenerative.org.au/webhook/regen_CAN/producers"
      range-product-categories="https://api.regenerative.org.au/webhook/regen/produce_categories"
      uniq="directory"
      route-prefix="directory"
    ></solid-ofn-rpp>
```

But the data issues have to be resolved before I can see if this works properly.

@karlafalk, try this version first. In Wordpress, replace the `<solid-ofn-rpp .... </solid-ofn-rpp>` with this snippet.

**Comment by David-OFN-CA** [comment]
**Context**

Referencing https://github.com/openfoodfoundation/sib-discovery-components/issues/60#issuecomment-2110534405 for context.

The data issues that Kirsten mentions above are associated with the JS errors we are getting in wordpress

@mkllnk explains that the JS error messages are coming up due to: 

> inconsistent data, which is a result of the fact that the producers list is pointing to Australian endpoints, like https://api.regenerative.org.au/webhook/regen/producer?id=recHkUWv8G0lfZFs1.
>  
> That raises an error, the component can't resolve the data and fails."

@mkllnk requests that we follow through in the following action item to help him resolve the issue 

**Tasks**

- [x] @karlafalk to go through the workflows and look for URLs that need updating? Every workflow defines URLs somewhere, but it may be in Set or in Code.
- [x] @mkllnk to rename n8n workflows for endpoints for easier discovery / navigation

**Comment by David-OFN-CA** [comment]
@kirstenalarsen @mkllnk - I think this resolves the data issues meaning that we can start to experiment with commenting out filters to simplify the components?

**Comment by mkllnk** [comment]
Yes, the data issues have been resolved. I can still see the full version on the test page. I put a minimal version here:

* https://regenerative.org.au/canada-test/

So you still need to copy the minimal version and then identify all the parts of the component that you don't want to show, like the products section in the producer details view. Hopefully we can hide them via CSS rules, otherwise we have to fork the component.

**Comment by David-OFN-CA** [comment]
@karlafalk when you get a chance, could you confirm that we've done this, and that everything is displaying as it should, and then we can close this issue? cheers

**Comment by karlafalk** [comment]
@David-OFN-CA @mkllnk We did add this code to our wordpress site and everything was worked fine:

     <solid-ofn-rpp
      producers-src="https://api.regenerative.org.au/webhook/regen_CAN/producers"
      range-product-categories="https://api.regenerative.org.au/webhook/regen/produce_categories"
      uniq="directory"
      route-prefix="directory"
      ></solid-ofn-rpp>
    
I can't confirm now as the wordpress site is currently being migrated/registered, and no longer visible to me. 

The big issue we found with the simplified version is that that code above is pulling 'produce_categories' as the filter menu and we probably want to simplify to 'assurance_partners' instead as that maps better to the group functionality we want to use for this project (Buy, Volunteer, Donate OFN groups).  We are not including any info related to product categories in this directory.

I am not sure if this is just a matter of replacing the "https://api.regenerative.org.au/webhook/regen/produce_categories" url with "https://api.regenerative.org.au/webhook/regen_CAN/assurance_partners" in the above code?

**Comment by mkllnk** [comment]
Changing the URL changes the data for the options displayed in the filter but it wouldn't work because it would still try to filter by product category. It would then just look for a product category named "Buy", for example.

**Comment by karlafalk** [comment]
@mkllnk So is there a way that we can have only the 'Assurances' (Group) filter to be displayed on the wordpress site and not the product categories info?

**Comment by mkllnk** [comment]
> is there a way that we can have only the 'Assurances' (Group) filter to be displayed on the wordpress site and not the product categories info?

Yes, but it's going to be a bit more complicated. I tried removing the URL for the product categories and the component was still displaying it. So we may have to look into the component and pull the parts out that we need.

Displaying the other filter should be as easy as adding this line again:
```
  range-producer-assurances="https://api.regenerative.org.au/webhook/regen_CAN/assurance_partners"
```

**Comment by mkllnk** [comment]
I updated my example and the volunteer filter has the Demo Hub in there: https://regenerative.org.au/canada-test/

**Comment by mkllnk** [comment]
Oh, actually, we can hide the category filter with this code above the component:
```html
<style>
div.row[name="set-line-produce"] { display: none }
</style>
```

**Comment by karlafalk** [comment]
Thanks @mkllnk.  That worked and now the product category field is hidden, and the only option is to filter by Assurance Partner (Group) so that is all good!
<img width="1571" alt="Screenshot 2024-05-31 at 10 00 11 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/805dc1f2-df09-4db3-9668-b7aa4c2f6908">

However, when I toggle to filter by 'Buy Waterloo' (1 enterprise) or 'Volunteer Waterloo' (both enterprises) I get no listings....
<img width="1574" alt="Screenshot 2024-05-31 at 10 00 34 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/04c7cd24-8837-4fee-9399-7de17f07ed21">

Even though I manually connected the Enterprise Name and assurance in Airtable.
<img width="1378" alt="Screenshot 2024-05-31 at 10 05 29 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/1a324452-74a6-4133-b13e-6b4452d5b367">

It seems to be related to a failure in the Airtable node in 'SIB workflow 7_Show assurance, list classifications, options'
<img width="1178" alt="Screenshot 2024-05-31 at 10 11 27 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/f190c118-49f1-49e6-833e-b1ecaade02c6">

<img width="1778" alt="Screenshot 2024-05-31 at 10 11 19 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/56493a43-561d-4b40-9558-2e2c5476e99b">

But I am not sure why it can't read Airtable when the persmissions are the same as they always have been?

**Comment by mkllnk** [comment]
Some executions succeed and others fail. That means that the credentials work. I just got another error:

> The service is receiving too many requests from you
> RATE_LIMIT_REACHED


Maybe we are triggering more than 5 requests per second?

https://airtable.com/developers/web/api/rate-limits

> Rate Limits
> 
> The API is limited to 5 requests per second per base.
> 
> Additionally, there is a limit of 50 requests per second for all traffic using personal access tokens from a given user or service account.
> 
> If you exceed these rates, you will receive a 429 status code and will need to wait 30 seconds before subsequent requests will succeed.

They recommend a caching proxy, which we do. So these errors should be temporary and disappear if you try again after a minute.

**Comment by karlafalk** [comment]
Ok thanks @mkllnk That makes sense and explains why sometimes the filtering does seem to work and other times not.  It sounds like changes (in Airtable) don't take effect immediately as the cached data is being displayed until requests through n8n can be sent for updates.  I probably wasn't waiting long enough.

**Comment by mkllnk** [comment]
The cache introduces a delay of 30 to 60 minutes.

**Comment by karlafalk** [comment]
@David-OFN-CA   The simplified component is working now so I think we can close this issue.
