### ISSUE TITLE
Compile List of Proposed Modification to Simplified Components

### ISSUE THREAD

**Issue by David-OFN-CA** [openfoodfoundation/sib-discovery-components#66]
OFN Canada team to review simplified SIB directory components and link to annotated figma designs, detailing proposed modifications.

**Comment by David-OFN-CA** [comment]
@RebeccaOFN when you get a chance this is where we should uplaod the Figma designs you are preparing

**Comment by RebeccaOFN** [comment]
Sorry for the delay. Here is the annotated design. Let me know if this is enough to understand our requested modifications, or if you need anything else (note that it's a prototype link but doesn't have functioning prototype elements). 
[Home page](https://www.figma.com/proto/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=3242-279&t=4Eu1cq48faTzUBIu-1)
[Producer page](https://www.figma.com/proto/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=4-229&t=4Eu1cq48faTzUBIu-1)

**Comment by karlafalk** [comment]
Hi @mkllnk Just flagging here the Producer page [https://www.figma.com/proto/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=4-230&t=4Eu1cq48faTzUBIu-1](url) design we were looking on feedback about. What changes would be possible?
 
We are basically looking for a simpler version of the Producer pages than is currently used for the AUS Discover Regen.  Would it be possible to modify the wordpress code to have things display as per the design mockup?  

It seems like the original Airtable base had space for 3 different wholesale URLs with labels. So presumably we could use these fields modified for our project.  So if we have a producer that does Buy Local, Volunteer Local, Donate Local, then could 3 different call to action buttons be displayed linked to different urls?

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/2f75dbe8-02ce-42d2-b5fd-ebd4a6b79e04)

**Comment by mkllnk** [comment]
> What changes would be possible?

From my end:

* Hiding things like the "useful links": easy.
* Changing text like "how to buy": possible.
* Re-arranging sections like moving about-section up: no. That requires a fork of the component.

**Comment by David-OFN-CA** [comment]
@mkllnk Just a quick update on this point: we decided that we will need to re-arranging sections and definitely move the about-section up to the top, in order to make this a fit for the needs of our partners. So I went ahead and got a quote from SiB, as I am getting a bit cocnerned about time as our deadline is end of September. 

SiB rates were very reasonable so **we are moving forward on forking the profile component**. Let us know if you want to be involved in discussion with SiB. We’ll of course keep tracking progress on this github project and will loop in the SiB dev here, once we  know who we are working with. 

**Additionally, I think we may have to fork the main directory component as well, in order to modify the design to include the toggle switch for “buy local, donate local” to the top of the display?** again, if you have any concerns to flag on this, or have other approaches to suggest, let me know

@kirstenalarsen - just pinging you on this update too, to keep you in the loop - let me know if you have concerns / suggestions on the approach. cheers all!

**Comment by karlafalk** [comment]
I have put together these screenshots with an itemized list of the changes we are looking for with the forked components for the Waterloo Project.  

**For the Home Page/Main Directory:**
<img width="1606" alt="Screenshot 2024-07-08 at 2 55 42 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/814962c0-6e7a-4fb4-9196-0a9b8f0e3c6d">

1) Change the ‘Assurance’ filter menu from dropdown menu to toggle menu across the top with 4 options (Eat Local, Donate Local, Volunteer Local, Show All).
2) Remove the Indigenous Flag
3) Is it possible/how much work is required (?) to change the ‘Produce types’ filter menu from a) a dropdown menu to a listview menu displayed on the left with an ‘Any’ option? (see this [figma design](https://www.figma.com/proto/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=3242-280&t=4Eu1cq48faTzUBIu-1)).
b) single-select to multi-select menu?
    What would the limit be to the number of categories we can have here? 
    At the very least, if none of these changes are possible, we would need to change the label ‘Produce types’ to ‘Category’.    
4) Can we remove the state and state code fields from displaying?
5) What are the default sort options?  Right now appears to be sorting Z to A.  Preference would be for sort A to Z.

**For the Producer Page:**
<img width="849" alt="Screenshot 2024-07-08 at 3 17 38 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/a4d3b251-3ead-426c-9909-564ce05e2b91">

1) Move the About Us section to the top of the page and have it display below the Producer Name (with City) and logo image.  This involves removing the state and state code fields, the Short description, ‘Learn More about us’ link, all info about Assurance Partners, and About Us heading.  See this [figma design](https://www.figma.com/proto/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=4-230&t=4Eu1cq48faTzUBIu-1).(Note: we want to keep the 'Useful links' section).  
2) Add Phone: xxxxx and Email: xxxx below the address info of the Location section.
3) Change the Heading ‘HOW TO BUY’ to ‘HOW TO SUPPORT’
4) Remove ‘WHOLESALE’ and ‘FEATURED’ headings.  Have the text here display all the way across the page.  Remove the ‘Connect with Producer’ button.
5) Have 3 call to actions here possible that go across the page in 3 columns.  (Not all producers will have all 3 options, many will likely have just one).  Highlight the call to actions with green blocks around them using the project colour scheme [(inserted] below) (note: these are not active buttons).  Include the ‘Visit Website’ link below each green block, as per original SiB.  
6) Remove the entire ‘Connect with Producer’ section.

![Screenshot 2024-06-28 155602](https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/7831ef24-b355-44e6-93c3-aec45eeff585)

**Comment by Louiscsn** [comment]
well received @karlafalk , thanks! I'm coordinating with the developers, and we will iterate to address the remaining questions :-)

**Comment by JbPasquier** [comment]
> Have 3 call to actions here possible that go across the page in 3 columns. (Not all producers will have all 3 options, many will likely have just one). Highlight the call to actions with green blocks around them using the project colour scheme [(inserted] below) (note: these are not active buttons). Include the ‘Visit Website’ link below each green block, as per original SiB.

Who will handle this change on your side? Can you provide me the field name that'll be used for these?

I guess the best approach would be a proper ldp:Container with a list of every links, this way a Producer could have 0...n links, it will adapt by itself. For each of them, I'll need a name and an url.

**Comment by karlafalk** [comment]
> Who will handle this change on your side? Can you provide me the field name that'll be used for these?
> 
> I guess the best approach would be a proper ldp:Container with a list of every links, this way a Producer could have 0...n links, it will adapt by itself. For each of them, I'll need a name and an url.

@JbPasquier We thought we could adapt the fields that are already in the AUS SiB and workflows.  They appear like this in Airtable:
<img width="1796" alt="Screenshot 2024-07-15 at 9 54 15 AM" src="https://github.com/user-attachments/assets/7fcefd29-3165-4333-acdd-ebac3eccdb9a">

So basically a field for each label (Buy Local, Volunteer Local or Donate Local) and a corresponding field for the respective url.  

These seem to get displayed with the label and url on the current AUS directory if the field 'Wholesale enquiry preference' has 'Direct online purchase' selected.  

Would this work in terms of the structure you suggested above?

**Comment by JbPasquier** [comment]
Thanks. Sure, that's fine, let's re-use these.

**Comment by Louiscsn** [comment]
hello @karlafalk 

I just had a meeting with @JbPasquier , we have a couple of questions for you with respect to the specs:

"Remove the Indigenous Flag" => only the flag, not the filter. Right?

"Is it possible/how much work is required (?) to change the ‘Produce types’ filter menu from a) a dropdown menu to a listview menu displayed on the left with an ‘Any’ option?" => the amount of work needed for this would exceed the current budget. Our estimate was based on a mockup where filters where hidden (cf. [here](https://www.figma.com/design/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=3237-2&t=f4yqEzVKtRdmRmkv-0)). If you still aim for having filters and would like to proceed with extra developments, we can have a call to refine your needs and share with you past reflections from OFN Australia?

"What are the default sort options? Right now appears to be sorting Z to A. Preference would be for sort A to Z." We can use any data for setting default sort options. Do I understand that you'd like to sort the list out of the project name?

As for the colors: how should we use them? :-) the interface is currently set with the color green, we understand you'd like it to be replaced with red (BB2028)? Maybe the buttons' colors should also be changed? If you can guide us, that would be helpful

Thanks!

**Comment by karlafalk** [comment]
Hello @JbPasquier @Louiscsn 

Thanks for your questions.

> "Remove the Indigenous Flag" => only the flag, not the filter. Right?  

Yes, we just want to remove the flag, NOT the filter.

> "Is it possible/how much work is required (?) to change the ‘Produce types’ filter menu from a) a dropdown menu to a listview menu displayed on the left with an ‘Any’ option?" => the amount of work needed for this would exceed the current budget. Our estimate was based on a mockup where filters where hidden (cf. [here](https://www.figma.com/design/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=3237-2&t=f4yqEzVKtRdmRmkv-0)). If you still aim for having filters and would like to proceed with extra developments, we can have a call to refine your needs and share with you past reflections from OFN Australia?

Ok that is understandable.  We weren't sure what would be involved.  I am not sure if we have extra funds in the budget to do this or would want to just leave as per the original scope.  @David-OFN-CA would be able to answer that.

> "What are the default sort options? Right now appears to be sorting Z to A. Preference would be for sort A to Z." We can use any data for setting default sort options. Do I understand that you'd like to sort the list out of the project name?

Yes, I think we would like the list to be sorted by the Enterprise/Organization name, A to Z.  @David-OFN-CA may have other thoughts on this as well.

> As for the colors: how should we use them? :-) the interface is currently set with the color green, we understand you'd like it to be replaced with red (BB2028)? Maybe the buttons' colors should also be changed? If you can guide us, that would be helpful

I think we mostly wanted the labels (Buy Local, Volunteer Local, Donate Local) above the weblinks in the How to Support section (Producer Page) to be in coloured green (74903C) blocks. I am not sure about the colour scheme for the rest of the elements and will have to get back to you about that.  @David-OFN-CA @RebeccaOFN may have thoughts on this.

Thanks! Please let us know if you have followup or additional questions.

**Comment by Louiscsn** [comment]
Notes following today's conversation with @David-OFN-CA :
- left filter menu: forget about the multi-select, drop the "Any" category
- top categories: add a "show all" button allowing to display all projects (as previously specified)

@JbPasquier tells us if there is a limit to the number of filters we can integrate in the menu on the left

@David-OFN-CA updates us tomorrow

**Comment by RebeccaOFN** [comment]
@JbPasquier @Louiscsn , just sharing our updated Figma designs with the proposed changes incorporated. 
[Directory ](https://www.figma.com/design/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=3242-279&t=B1lWW5BTckMK0AHN-0)
[Profile Page  ](https://www.figma.com/design/tg4fv1yC8vXx57GRtKQ72B/Waterloo?node-id=4-229&t=B1lWW5BTckMK0AHN-0)

**Comment by karlafalk** [comment]
Hello @JbPasquier I just wanted to touch base to see how things are coming along with the changes to the SiB components?  

Please let me know if I can help clarify and/or test anything?  Do you have an estimated timeline for completion?  

Thanks!

**Comment by JbPasquier** [comment]
Hi @karlafalk, I haven't deep dived into these yet, but those figma designs are awesome! They'll greatly help me to fit the component to your needs.

I think that I have all that I need. I have a few tasks to complete first, and I should be able to start on the 8th, I'll be dedicated to your component and should be able to deliver by the 14th at the latest.

**Comment by karlafalk** [comment]
Hi @JbPasquier Thanks for the update & timeline.  We look forward to seeing the modified components!  Just a note - I will be away starting Aug 10th (till Sept 10th) so please ping @David-OFN-CA here if you have any questions.  Thank you!

**Comment by JbPasquier** [comment]
@karlafalk  I've postponed some of my other tasks to allow you to review the Waterloo component before your vacation.
@David-OFN-CA @RebeccaOFN 

I've made an adaptation based on the current mockup. Please note that the AUS data are not tailored to your designs, so instead of "Eat Local," "Give Local," etc., you will find their Assurances.

Demo : https://ofn-regenerative.startinblox.com/

Feel free to share your data server URL with me, so I can update the demo.

Integration guide : https://git.startinblox.com/components/ofn-rpp/-/blob/waterloo/INTEGRATION.md

The integration process will be similar to that of the AUS component. I believe @mkllnk should be able to assist if necessary.

**Comment by karlafalk** [comment]
Thanks @JbPasquier for fast tracking this project!  

I think the Demo page looks great and reflective of the mockups we sent along.  I will let @David-OFN-CA and @RebeccaOFN comment as well.  

Also, @RebeccaOFN will be able to share the wordpress/data server URL with you.  

So are the next steps for us to Integrate OFN RPP Component (code) into WP?  Will the 'Assurances' then change to the Eat Local, Give Local, Grow Local toggles since it will be linked to our Airtable?  What about the 'See all' option?

**Comment by JbPasquier** [comment]
> So are the next steps for us to Integrate OFN RPP Component (code) into WP?

Correct.

> Also, @RebeccaOFN will be able to share the wordpress/data server URL with you.

@RebeccaOFN I'll need the equivalent of these routes:

- https://api.regenerative.org.au/webhook/regen/producer-bundle
- https://api.regenerative.org.au/webhook/regen/produce_categories
- https://api.regenerative.org.au/webhook/regen/assurance_partners

> Will the 'Assurances' then change to the Eat Local, Give Local, Grow Local toggles since it will be linked to our Airtable? 

Yes, as long as you create those 3 values and properly link them to your producers.
Note that you'll be able to add as many other entries as you want without any changes on the component side; these are data-driven.

> What about the 'See all' option?

I wasn't sure about the purpose of this link. I made each 'Assurance' as some kind of toggle, let me know if that's not enough.

**Comment by karlafalk** [comment]
Also @JbPasquier, one other issue I have noticed and been playing with is that the 'Indigenous led' toggle hasn't been working for us correctly with the original AUS component.  @mkllnk gave us some style code to change the label name for the Waterloo Project. This however only changed the label of the menu.  We still needed to keep the label as 'First Nation led' (AUS terminology) in the Airtable for the sorting to work correctly on the wordpress site.  This is fine (we can use First Nations in our Airtable column label), however this results in the tag for the Producer being 'First Nations led' where we want it to appear as 'Indigenous led'.  

I am not sure it this requires a change in our n8n workflows or the StartinBlox code?  I tried changing the n8n workflow - "Show Producer - Regen Produce code' block (the only one where I could find 'First Nations led' filter mentioned in all the n8n workflows) from 'First Nations led' to 'Indigenous led', and the Airtable colulmn heading from 'First Nations led' to 'Indigenous led', but this didn't seem to work (have since changed them back).  

<img width="2175" alt="Screenshot 2024-08-02 at 7 31 11 AM" src="https://github.com/user-attachments/assets/18937155-b46a-4dc8-9875-1cfa8fc211c6">
<img width="864" alt="Screenshot 2024-08-06 at 7 56 16 AM" src="https://github.com/user-attachments/assets/ed4f5424-307e-4624-aaf0-49ddb6cafac9">

It seems like this toggle is working properly though on the Demo site sent above?  So maybe something had to be changed in the SIB components?  Let me know if I should change the Airtable column heading to 'Indigenous led' to match the filter heading?

**Comment by JbPasquier** [comment]
A bit of technical detail about this: The component expects an ofn:First_Nations_led field within the resource. This can be directly a field or another key pointed to by its context.

There are four solutions here:
- Rename this field both in the API (n8n) and in the component (SIB side).
- Rename this column in your Airtable, but let n8n serialize it into the ofn:First_Nations_led field.
- Create a new column, in addition to the First Nations led one, serialized as its own field.
- Keep it as is, it'll work and show visually "Indigenous led"

As I don’t know how things are implemented on the n8n side, I can’t really help you with the second solution.

Let me know if you want me to adapt the component to the first or the third solution. I’ll need the definitive field name.

Please note that if we follow the first solution, and if one day you want to federate your data with others, yours will be incompatible with the AUS ones. The third solution might be a better fit.

**Comment by karlafalk** [comment]
> @RebeccaOFN I'll need the equivalent of these routes:
> 
>     * https://api.regenerative.org.au/webhook/regen/producer-bundle
> 
>     * https://api.regenerative.org.au/webhook/regen/produce_categories
> 
>     * https://api.regenerative.org.au/webhook/regen/assurance_partners

@JbPasquier - Ok sorry I thought the URL was for the wordpress server/website.   I can provide the equivalent of the above that we have been using for the Waterloo project. (We basically just added '_CAN' after regen for all of them).

https://api.regenerative.org.au/webhook/regen_CAN/producers
https://api.regenerative.org.au/webhook/regen_CAN/produce_categories
https://api.regenerative.org.au/webhook/regen_CAN/assurance_partners

NOTE: up until now we have been using 'producers' vs 'produce-bundle' as per @mkllnk instructions:

'You need to use producers instead of producer-bundle and products instead of product-bundle. The bundles are for performance only and we just added them in the last weeks. We can add them to your stack when everything is working.'

@mkllnk Not sure at which point we should move to the 'producer-bundle' instead for performance, and how we go about doing this?

**Comment by JbPasquier** [comment]
It works. :-)

A little slow, it will behave much better when you'll have the bundle route.

**Comment by karlafalk** [comment]
> * Keep it as is, it'll work and show visually "Indigenous led"

@JbPasquier  I think we would go with this option, but right now the 'Waterloo Fillout Form Test' enterprise should be displaying as 'Indigenous led' .  It has 'Yes' selected under 'First Nations led' in the Airtable.  But it does not come up when Indigenous led is toggled.

With the new component maybe I should try changing the n8n workflow - "Show Producer - Regen Produce code' block filter label back to 'Indigenous led' and the Airtable field heading back to 'Indigenous led' to see if then gets filtered correctly?

**Comment by karlafalk** [comment]
> > What about the 'See all' option?
> 
> I wasn't sure about the purpose of this link. I made each 'Assurance' as some kind of toggle, let me know if that's not enough.

I see what you mean - each option (Eat Local, Give Local, Grow Local) can be toggled on/off, so if you want to see all of the listings, you just toggle them all off.  Perhaps this works fine for us, and we don't need a 'see all' option?  @David-OFN-CA @RebeccaOFN

**Comment by JbPasquier** [comment]
I do see both producers with the filter:

![image](https://github.com/user-attachments/assets/96a8501d-862e-42d7-b11b-1509f08739e9)

From what I see on your datas, maybe you're expecting Demo Shop to not show as Indigenous led.

I see that AUS datas are like this :
```
"ofn:First_Nations_led": true
```
```
"ofn:First_Nations_led": false
```

And yours are like that:
```
  "ofn:First_Nations_led": [
    "Yes"
  ],
```
```
  "ofn:First_Nations_led": [
    "No"
  ],
```

Can it be fixed to a boolean instead of an array?

**Comment by karlafalk** [comment]
@JbPasquier This is what we have in Airtable for those 2 producers:

<img width="1231" alt="Screenshot 2024-08-06 at 8 58 58 AM" src="https://github.com/user-attachments/assets/cea3b5be-d781-4911-9651-77e2b6950038">

So only one should be showing up with the Indigenous toggle.  

So should I just change our Airtable to be 'true' instead of 'Yes' and 'false' instead of 'No'?  That is easy enough, if that is the case.

**Comment by JbPasquier** [comment]
> So should I just change our Airtable to be 'true' instead of 'Yes' and 'false' instead of 'No'? That is easy enough, if that is the case.

I'll let @mkllnk answer this one. I don't know how things are handled on your end in n8n.

But yes, that's the idea: serve a boolean instead of an array of strings.
Do you have access to the Australian one? Maybe you can compare it with yours to see where the difference lies.

**Comment by karlafalk** [comment]
> But yes, that's the idea: serve a boolean instead of an array of strings.
> Do you have access to the Australian one? Maybe you can compare it with yours to see where the difference lies.

Ahhh, yes!  It looks like that is where the problem lies.  At some point we had changed from a 'checkbox' to a Yes/No.  (I had a copy of the original Airtable base from AUS to check this against).  Thanks for your help!  I will try changing back to a checkbox and see if that fixes things.

**Comment by karlafalk** [comment]
@JbPasquier - Just working on this step:
> > So are the next steps for us to Integrate OFN RPP Component (code) into WP?
>
I have added the code to our wordpress site:
<img width="1487" alt="Screenshot 2024-08-06 at 10 10 38 AM" src="https://github.com/user-attachments/assets/6e9743ba-7104-4244-b08e-50076c92837c">

I replaced 'some-path' with 'directory' as that is what we had there before.  Maybe it should be something different?

It updated things, but there a number of things that aren't displaying correctly. 
<img width="1524" alt="Screenshot 2024-08-06 at 10 15 34 AM" src="https://github.com/user-attachments/assets/ec95e3ab-02a2-4eb3-b00f-2ae52c9099e6">

As well the producer page, has not really been re-configured at all. 

BUT this is likely because I didn't complete all the steps:

<img width="1452" alt="Screenshot 2024-08-06 at 10 17 58 AM" src="https://github.com/user-attachments/assets/fc2679fd-2fd0-4df7-8172-4ae8645f6695">

Is this step done on the wordpress site? 

<img width="1481" alt="Screenshot 2024-08-06 at 10 18 50 AM" src="https://github.com/user-attachments/assets/d62efed0-21bb-45b0-876f-c5f59b968946">

Where do I do this step? Is this just pasted below the main code blocks listed above?

**Comment by JbPasquier** [comment]
I forced a purge of the jsdelivr's CDN cache. Can you check it again?

> Is this step done on the wordpress site?

Yes. This last step is to allow a direct load of producer details pages. Not related to your issue. Usually within the .htaccess file beside your wordpress.

> Where do I do this step? Is this just pasted below the main code blocks listed above?

You will not need this one, as you don't have a products list page, you can use a direct link to your wordpress page which integrate the component.

**Comment by karlafalk** [comment]
@JbPasquier Ok thanks.  I rechecked things and I am still getting the same result (although in the past I have found it can take quite awhile for changes to appear 'live' on the wordpress site).  

ARe you able to see things here on our staging site - [https://waterlooregionfood.ca/staging/5285/](not sure if you need a password to view?).

I will talk to @RebeccaOFN about making that change to .htaccess on the wordpress site.

**Comment by JbPasquier** [comment]
Looks like I have it up-to-date from here:

![image](https://github.com/user-attachments/assets/da47ab29-63f5-4746-8dfc-c2c6c5298027)

jsDelivr's CDN cache can be pretty aggressive, and you may use a different server from CAN than me from FRA. Usually they're automatically updated after 24h max. 
Can you try to reach [this URL](https://www.jsdelivr.com/tools/purge) and type : `https://cdn.jsdelivr.net/npm/@startinblox/component-ofn-rpp@waterloo` then press "Purge now".
If it does not work, maybe try in a private browsing session.

**Comment by karlafalk** [comment]
Thanks @JbPasquier!  

The purge worked, but didn't seem to change anything.  But, the private browsing did work!  Everything is coming through now.  And the Indigenous toggle is working correctly!

The only thing I noticed is about the spacing...not sure if this is controlled by startin'blox, but is it possible to have a wider column on the left side of the producer page, so the contact details can be fully displayed?  

<img width="934" alt="Screenshot 2024-08-06 at 11 09 08 AM" src="https://github.com/user-attachments/assets/22d485dd-4290-43ac-8f55-a07ebf8561d8">

**Comment by RebeccaOFN** [comment]
@JbPasquier , I haven't worked with the .htaccess file or rewrite rules before. Are you able to talk me through this at all?

**Comment by JbPasquier** [comment]
> The only thing I noticed is about the spacing...not sure if this is controlled by startin'blox, but is it possible to have a wider column on the left side of the producer page, so the contact details can be fully displayed?

I've pushed some change to the left part of the component to use 1/3 instead of 1/4th of its container.

I'd still advise to give a wider space to the component from WP.

You may face the same cache issue as before, purging CDN + private browsing may help.

Edit, for reference:

![image](https://github.com/user-attachments/assets/b7d88ba6-1a43-4a98-a252-cf1727cf73c2)

> I haven't worked with the .htaccess file or rewrite rules before. Are you able to talk me through this at all?

Sure, where your WP files lies you should have an `.htaccess` hidden file, in the same folder as the `index.php`.

Edit this file with your favorite code editor, a simple text editor is enough. 
It should look like something like that (May differ, if you use plugin or a special configuration):
```
# BEGIN WordPress
...
RewriteEngine On
...
RewriteBase /
...
# END WordPress
```

Within those lines, after the RewriteBase but preferably before other rules, add this one `RewriteRule ^my-page/.+$ /my-page/ [L]` where `my-page` is the same value as the route-prefix of the component (= path to your page, for instance your demo page is: `staging/5285`).

Depending on your hosting platform, you may also need this line:
```
AllowEncodedSlashes NoDecode
```

We had some trial and error with @mkllnk to make it work for the AUS WP, he may be able to provide a complete htaccess fitting your needs.

**Comment by RebeccaOFN** [comment]
Thanks @JbPasquier , I added that line. How will I know if it's done what it's supposed to do or if I just broke everything, lol?

**Comment by JbPasquier** [comment]
> How will I know if it's done what it's supposed to do or if I just broke everything, lol?

You should be able to F5 on a producer details page.

**Comment by RebeccaOFN** [comment]
So, I'm guessing this is not what we want. 
![Screenshot 2024-08-06 121142](https://github.com/user-attachments/assets/b931eca4-08ed-4cfc-bc7a-c3e4de0190a1)

**Comment by JbPasquier** [comment]
It may be related with this:

> I replaced 'some-path' with 'directory' as that is what we had there before. Maybe it should be something different?

@karlafalk Can you try with `staging/5285` there too?

**Comment by karlafalk** [comment]
> I've pushed some change to the left part of the component to use 1/3 instead of 1/4th of its container.
> 
> I'd still advise to give a wider space to the component from WP.
> 
> You may face the same cache issue as before, purging CDN + private browsing may help.

@JbPasquier That looks better on your demo site, but I am not seeing the changes come through on our staging site.  I have done another 'purge' and used private browsing, but the spacing hasn't seemed to change for me?? Also, just wondering how the private browsing works...is that just an issue on our end with caching? or will customers who visit the site also have issues if they are not using private browsing?

**Comment by karlafalk** [comment]
> It may be related with this:
> 
> > I replaced 'some-path' with 'directory' as that is what we had there before. Maybe it should be something different?
> 
> @karlafalk Can you try with `staging/5285` there too?

I changed the path to the suggestion above.  Maybe you can try your check again with F5 @RebeccaOFN?

**Comment by JbPasquier** [comment]
> Also, just wondering how the private browsing works...is that just an issue on our end with caching? or will customers who visit the site also have issues if they are not using private browsing?

There are two kinds of caches used here : One from the CDN and one on your browser.
CDN are composed of different servers distributed all around the world, you can manually purge only the one you're connected to with jsdelivr, it expire within 24h - 7 days max.
Your browser's cache usually expire after 24h at most.
Good news are that your future customers shouldn't be impacted, as we'll serve them the final version of the component. Here we're impacted because we're using a development version in production.

You can check which version is served to your browser here: https://cdn.jsdelivr.net/npm/@startinblox/component-ofn-rpp@waterloo on third line it should say `2.1.0-waterloo.3`.

**Comment by RebeccaOFN** [comment]
> > It may be related with this:
> > > I replaced 'some-path' with 'directory' as that is what we had there before. Maybe it should be something different?
> > 
> > 
> > @karlafalk Can you try with `staging/5285` there too?
> 
> I changed the path to the suggestion above. Maybe you can try your check again with F5 @RebeccaOFN?

I'm still seeing the same error.

**Comment by JbPasquier** [comment]
Can you share your htaccess file?

**Comment by RebeccaOFN** [comment]
[htaccess.txt](https://github.com/user-attachments/files/16514477/htaccess.txt)

**Comment by JbPasquier** [comment]
Can you try with this one?

[htaccess.txt](https://github.com/user-attachments/files/16514608/htaccess.txt)

**Comment by RebeccaOFN** [comment]
That seems to have broken the site completely. Main page is now showing this error. 
![Screenshot 2024-08-06 150302](https://github.com/user-attachments/assets/05a48b98-d903-447a-b2b6-02805623c726)

**Comment by JbPasquier** [comment]
:-)

May I suggest you to rollback to the previous one and ask @mkllnk what he implemented on the OFN AUS one.

**Comment by RebeccaOFN** [comment]
> :-)
> 
> May I suggest you to rollback to the previous one and ask @mkllnk what he implemented on the OFN AUS one.

Will do!

**Comment by RebeccaOFN** [comment]
@mkllnk , if you can share your htaccess file that would be awesome.

**Comment by David-OFN-CA** [comment]
I'm closing this thread as the orginal issue has been addressed. will open a new issue to address the request for a htaccess file, which is still open
